name: CI

on:
  push:
    branches:
      - '*' 

jobs:
  validate-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate commit message format
        run: bash ci/check_commit_message.sh $GITHUB_EVENT_PATH

